name: preview-comment

on:
  workflow_run:
    workflows:
      - preview-run
    types:
      - requested

permissions:
  contents: read
  issues: write
  pull-requests: write

concurrency: preview-comment

jobs:
  preview-comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19
      - name: Install some tools
        run: |
          sudo apt update
          sudo apt install -y ncat
          wget https://github.com/FiloSottile/age/releases/download/v1.1.1/age-v1.1.1-linux-amd64.tar.gz
          tar xzf age-v1.1.1-linux-amd64.tar.gz
          sudo mv age/age* /usr/bin/
      - name: Install ipfs
        run: |
          wget -q https://dist.ipfs.tech/kubo/v0.20.0/kubo_v0.20.0_linux-amd64.tar.gz
          tar -xvzf kubo_v0.20.0_linux-amd64.tar.gz
          ./kubo/install.sh
      - name: ipfs init
        run: |
          ipfs init
          ipfs config --json Experimental.Libp2pStreamMounting true
          ipfs config --json Ipns.UsePubsub true
          ipfs daemon &
          sleep 1
          while ! ipfs id &> /dev/null; do
            echo "waiting for the daemon"
            sleep 1
          done
      - name: Import ipfs key
        run: |
          echo "${{ secrets.KLUCTL_PREVIEW_IPNS_KEY }}" | base64 -d > kluctl-preview-comment.pem
          ipfs key import kluctl-preview-comment kluctl-preview-comment.pem -f pem-pkcs8-cleartext
      - name: Build ipfs-exchange-info
        run: |
          (cd ./hack/ipfs-exchange-info && go build ./)
      - name: Publish own ID
        run: |
          ./hack/ipfs-exchange-info/ipfs-exchange-info -mode publish-ipns -workflow-run-id ${{ github.event.workflow_run.id }} --ipns-key kluctl-preview-comment
      - name: Receive info
        id: info
        run: |
          echo "${{ secrets.KLUCTL_PREVIEW_AGE_KEY }}" > age.key
          while ! ./hack/ipfs-exchange-info/ipfs-exchange-info -mode receive-info -workflow-run-id ${{ github.event.workflow_run.id }} \
            --age-key-file age.key --repo-name "${{ github.repository }}" > info.json; do
            sleep 1
          done

          cat info.json | jq ".ipfsId" -r > ipfs_id
          cat info.json | jq ".staticIpnsName" -r > static_ipns_name
          cat info.json | jq ".prNumber" -r > pr_number

          echo "ipfs_id=$(cat ipfs_id)"
          echo "static_ipns_name=$(cat static_ipns_name)"
          echo "pr_number=$(cat pr_number)"

          echo "ipfs_id=$(cat ipfs_id)" >> $GITHUB_OUTPUT
          echo "pr_number=$(cat pr_number)" >> $GITHUB_OUTPUT
      - name: Build comment text
        run: |
          cat <<EOF > comment.md
          # 🤖 Preview Environment
          The preview environment is starting up and will be available in a few minutes.
          
          # Accessing the static preview UI
          This version of the UI is static but updated regularly. The updates will lag quite a lot, as IPFS needs
          some time to propagate changes. You'd also need to refresh the page to get an update.
          
          The public gateway url is: https://ipfs.io/ipns/$(cat static_ipns_name)/index.html
          
          # Accessing the dynamic preview UI
          First, install and start [IPFS Kubo](https://github.com/ipfs/kubo/) locally.
          Then run the \`http\` forward command from below.
          After that, the UI will be accessible through http://localhost:9090.
          
          IPFS forward commands:
          http: \`ipfs p2p forward /x/kluctl-webui /ip4/127.0.0.1/tcp/9090 /p2p/$(cat ipfs_id)\`
          ssh: \`ipfs p2p forward /x/ssh /ip4/127.0.0.1/tcp/2222 /p2p/$(cat ipfs_id)\`
          k8s: \`ipfs p2p forward /x/k /ip4/127.0.0.1/tcp/6443 /p2p/$(cat ipfs_id)\`
          
          When asked for credentials, use admin:admin.
          
          # Shutting it down
          Either cancel the pipeline in the PR or simply wait for 30 minutes until it auto-terminates.
          EOF
      - uses: mshick/add-pr-comment@v2
        with:
          issue: ${{ steps.info.outputs.pr_number }}
          message-id: preview-run-info
          message-path: |
            comment.md
