name: preview-comment

on:
  workflow_run:
    workflows:
      - preview-run
    types:
      - requested

permissions:
  contents: read
  issues: write
  pull-requests: write

concurrency: preview-comment

jobs:
  preview-comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19
      - name: Install some tools
        run: |
          sudo apt update
          sudo apt install -y ncat
          wget https://github.com/FiloSottile/age/releases/download/v1.1.1/age-v1.1.1-linux-amd64.tar.gz
          tar xzf age-v1.1.1-linux-amd64.tar.gz
          sudo mv age/age* /usr/bin/
      - name: Install ipfs
        run: |
          wget -q https://dist.ipfs.tech/kubo/v0.20.0/kubo_v0.20.0_linux-amd64.tar.gz
          tar -xvzf kubo_v0.20.0_linux-amd64.tar.gz
          ./kubo/install.sh
      - name: ipfs init
        run: |
          ipfs init
          ipfs config --json Experimental.Libp2pStreamMounting true
          ipfs daemon &
          sleep 5
      - name: Import ipfs key
        run: |
          echo "${{ secrets.KLUCTL_PREVIEW_IPNS_KEY }}" | base64 -d > kluctl-preview-comment.pem
          ipfs key import kluctl-preview-comment kluctl-preview-comment.pem -f pem-pkcs8-cleartext
      - name: Publish own ID
        run: |
          (cd ./hack/ipfs-exchange-info && go build ./)
          ./hack/ipfs-exchange-info/ipfs-exchange-info -mode publish-ipns -workflow-run-id ${{ github.event.workflow_run.id }} --ipns-key kluctl-preview-comment
      - name: Receive info
        id: info
        run: |
          echo "${{ secrets.KLUCTL_PREVIEW_AGE_KEY }}" > age.key
          while ! go run ./hack/ipfs-exchange-info/ipfs-exchange-info -mode receive-info -workflow-run-id ${{ github.event.workflow_run.id }} \
            --age-key-file age.key --repo-name "${{ github.repository }}" > info.json; do
            sleep 1
          done

          cat info.json | jq ".ipfs_id" -r > ipfs_id
          cat info.json | jq ".pr_number" -r > pr_number

          echo "ipfs_id=$(cat ipfs_id)"
          echo "pr_number=$(cat pr_number)"

          echo "ipfs_id=$(cat ipfs_id)" >> $GITHUB_OUTPUT
          echo "pr_number=$(cat pr_number)" >> $GITHUB_OUTPUT
      - name: Build comment text
        run: |
          cat <<EOF > comment.md
          # 🤖 Preview Environment
          The preview environment is starting up.
          
          # ipfs forward commands
          http: \`ipfs p2p forward /x/kluctl-webui /ip4/127.0.0.1/tcp/9090 /p2p/$(cat ipfs_id)\`
          ssh: \`ipfs p2p forward /x/ssh /ip4/127.0.0.1/tcp/9090 /p2p/$(cat ipfs_id)\`
          k8s: \`ipfs p2p forward /x/k /ip4/127.0.0.1/tcp/9090 /p2p/$(cat ipfs_id)\`
          EOF
      - uses: mshick/add-pr-comment@v2
        with:
          issue: ${{ steps.info.outputs.pr_number }}
          message-id: preview-run-info
          message-path: |
            comment.md
