name: preview-build

on:
  pull_request:
    types: [labeled, synchronize]
    branches:
      - main

jobs:
  preview-build:
    if: ${{ github.event.label.name == 'preview' || contains(github.event.pull_request.labels.*.name, 'preview') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-preview-build-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-preview-build-
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19
      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      # BUILD
      - name: Build binary
        run: |
          go build -o bin/kluctl cmd/main.go
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          load: true
          tags: kluctl:preview
      - name: Store image
        run: docker save kluctl:preview > kluctl-preview.tar
      - uses: actions/upload-artifact@v3
        with:
          name: kluctl-preview-image
          path: kluctl-preview.tar

