name: preview-build-binary

on:
  pull_request:
    types: [labeled, synchronize]
    branches:
      - main

jobs:
  ipfs-init:
    # only run on preview-branches and on PRs with the preview label
    if: ${{ github.event.label.name == 'preview' || contains(github.event.pull_request.labels.*.name, 'preview') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-preview-webui-init-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-preview-webui-init-
      - name: Install ipfs
        run: |
          wget https://dist.ipfs.tech/kubo/v0.20.0/kubo_v0.20.0_linux-amd64.tar.gz
          tar -xvzf kubo_v0.20.0_linux-amd64.tar.gz
          ./kubo/install.sh
      - name: ipfs init
        run: |
          ipfs init
      - uses: actions/upload-artifact@v3
        with:
          name: ipfs-config
          path: ~/.ipfs

#  push-preview-docker:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#        with:
#          fetch-depth: 0
#      - uses: actions/cache@v3
#        with:
#          path: |
#            ~/go/pkg/mod
#            ~/.cache/go-build
#          key: ${{ runner.os }}-push-preview-docker-${{ hashFiles('**/go.sum') }}
#          restore-keys: |
#            ${{ runner.os }}-push-preview-docker-
#      - name: Set up Go
#        uses: actions/setup-go@v4
#        with:
#          go-version: 1.19
#      - name: Setup Docker Buildx
#        id: buildx
#        uses: docker/setup-buildx-action@v2
#      - name: Print metadata
#        run: |
#          echo "tags=${{ steps.meta.outputs.tags }}"
#          echo
#          echo "labels=${{ steps.meta.outputs.labels }}"
#          echo
#      - name: Build binary
#        run: |
#          go build -o bin/kluctl cmd/main.go
#      - name: Build and push Docker image
#        uses: docker/build-push-action@v4
#        with:
#          context: .
#          push: true
#          tags: ${{ steps.meta.outputs.tags }}
#          labels: ${{ steps.meta.outputs.labels }}
#          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache
#          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache,mode=max
#      - name: Post link
#        if: ${{ github.event.issue != 0 }}
#        uses: mshick/add-pr-comment@v2
#        with:
#          message: |
#            **Hello**
#            🌏Here is the link to your preview environment: https://preview-pr-${{ github.event.issue }}.kluctl-demo.kluctl.io
